from __future__ import annotations

from forge.buildfile import parse
from forge.ninjaexport import (
    edges_of_make,
    to_make,
    to_ninja,
    verify_make_export,
)

PROJECT = """
source = main.c
source = lib.c

rule = main.o
command = cc -O2
reads = main.c
writes = main.o
needs = main.c

rule = lib.o
command = cc -O2
reads = lib.c
writes = lib.o
needs = lib.c

rule = app
command = ld
reads = main.o, lib.o
writes = app
needs = main.o, lib.o
"""


class TestMake:
    def test_the_makefile_carries_every_edge(self):
        exported = to_make(parse(PROJECT))
        edges = edges_of_make(exported)
        assert ("app", "main.o") in edges
        assert ("app", "lib.o") in edges
        assert ("main.o", "main.c") in edges

    def test_recipes_follow_their_targets(self):
        lines = to_make(parse(PROJECT)).splitlines()
        target_line = lines.index("app: lib.o main.o")
        assert lines[target_line + 1] == "\tld"

    def test_the_export_is_deterministic(self):
        assert to_make(parse(PROJECT)) == to_make(parse(PROJECT))

    def test_verification_passes_an_honest_export(self):
        exported = verify_make_export(parse(PROJECT))
        assert exported.startswith("# generated by forge")


class TestNinja:
    def test_identical_commands_share_one_rule(self):
        exported = to_ninja(parse(PROJECT))
        assert exported.count("rule r") == 2
        assert exported.count("command = cc -O2") == 1

    def test_build_statements_name_their_inputs(self):
        exported = to_ninja(parse(PROJECT))
        assert "build app:" in exported
        assert "lib.o main.o" in exported

    def test_the_export_is_deterministic(self):
        assert to_ninja(parse(PROJECT)) == to_ninja(parse(PROJECT))
