"""Export to other build systems: the graph outlives any one runner.

A graph that only this engine can execute is a lock-in wearing a
feature's clothes. The exporters emit the same targets in two
foreign dialects: a Makefile whose recipes preserve dependency
order and phony aggregate, and a ninja file with build statements
and a rule per distinct command. Both exports are deterministic,
sorted the same way twice, because a generated file that diffs on
every generation poisons code review for everyone downstream. The
round-trip check is the honest part: the export is re-parsed and
its edge set compared to the source graph's, so a target dropped
or an edge inverted fails the export rather than the customer, and
the comparison is by set equality since foreign formats are free
to reorder what they must not reshape.
"""

from __future__ import annotations

from forge.buildfile import BuildFile
from forge.errors import Invalid


def to_make(parsed: BuildFile) -> str:
    lines = [
        "# generated by forge; do not edit",
        ".PHONY: all",
        f"all: {' '.join(sorted(parsed.stanzas))}",
        "",
    ]
    for name in sorted(parsed.stanzas):
        stanza = parsed.stanzas[name]
        prerequisites = " ".join(sorted(stanza.needs))
        outputs = " ".join(stanza.writes)
        lines.append(f"{outputs}: {prerequisites}")
        lines.append(f"\t{stanza.command}")
        lines.append("")
    return "\n".join(lines)


def to_ninja(parsed: BuildFile) -> str:
    commands = sorted(
        {stanza.command for stanza in parsed.stanzas.values()}
    )
    rule_names = {
        command: f"r{number}" for number, command in enumerate(commands)
    }
    lines = ["# generated by forge; do not edit", ""]
    for command in commands:
        lines.append(f"rule {rule_names[command]}")
        lines.append(f"  command = {command}")
        lines.append("")
    for name in sorted(parsed.stanzas):
        stanza = parsed.stanzas[name]
        outputs = " ".join(stanza.writes)
        inputs = " ".join(sorted(stanza.reads))
        implicit = sorted(set(stanza.needs) - set(stanza.reads))
        tail = f" | {' '.join(implicit)}" if implicit else ""
        lines.append(
            f"build {outputs}: {rule_names[stanza.command]} "
            f"{inputs}{tail}".rstrip()
        )
    lines.append("")
    return "\n".join(lines)


def edges_of_make(text: str) -> set[tuple[str, str]]:
    found = set()
    for line in text.splitlines():
        if (
            not line
            or line.startswith(("#", "\t", "."))
            or line.startswith("all:")
        ):
            continue
        if ":" in line:
            outputs, _, prerequisites = line.partition(":")
            for output in outputs.split():
                for need in prerequisites.split():
                    found.add((output, need))
    return found


def verify_make_export(parsed: BuildFile) -> str:
    exported = to_make(parsed)
    want = {
        (write, need)
        for stanza in parsed.stanzas.values()
        for write in stanza.writes
        for need in stanza.needs
    }
    got = edges_of_make(exported)
    if got != want:
        missing = want - got
        extra = got - want
        raise Invalid(
            f"the export lies: missing {sorted(missing)}, "
            f"invented {sorted(extra)}"
        )
    return exported
